### ISSUE TITLE
Check Plugin mapping

### ISSUE THREAD

**Issue by settoger** [philippbosch/cordova-osc-plugin#1]
Hello,
I got this error, when I try to build my App
`ERROR: Plugin 'OSC' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.`
Is this plugin compatible with the newest version of Cordova?

**Comment by philippbosch** [comment]
Most probably not. Haven't used it in years. Sorry … 

Happy to accept a PR if you get it to work though.
